!feat: Minor release is done

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -222,7 +222,7 @@ jobs:
             fi
 
             docker compose pull app || { echo "Failed to pull tagged image"; exit 1; }
-            docker compose up -d || { echo "Failed to start containers"; exit 1; }
+            sudo docker compose up -d --force-recreate --scale app=3 || { echo "Failed to start containers"; exit 1; }
 
             echo "Manual deployment completed successfully."
  
